apiVersion: v1
kind: Service
metadata:
  name: kh2-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: kh2-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kh2-server
  labels:
    app: kh2-server
    version: 1.0.0
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kh2-server
  template:
    metadata:
      labels:
        app: kh2-server
    spec:
      containers:
      - name: kh2-server
        image: jhobz/kh2-server:latest
        ports:
        - containerPort: 80