/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface KH2ItemMessage {
  /**
   * The name of the item.
   */
  name: string;
  /**
   * The location ID at which the item was collected.
   */
  location: string;
  /**
   * The player from which the item was collected.
   */
  from?: number;
  /**
   * The player to whom the item was sent.
   */
  to?: number;
}
