name: Deploy

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build on Node 18
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@main
              
      - name: Log in to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        
      - name: Build container image
        run: docker build -t docker.io/jhobz/kh2-server:latest .

      - name: Push image
        run: docker push docker.io/jhobz/kh2-server:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2.2.0
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Configure doctl
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 jhobz-projects-cluster

      - name: Deploy
        run: kubectl rollout restart deployment kh2-server
