name: Deploy

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build on Node 18
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  deploy:
    name: Deploy KH2 Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Node.js app
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          script: |
            git clone git@github.com:jhobz/kh2-server.git
            npm i --production
            npm run build
            pm2 restart "KH2 Server"
